# HEBI Robot Config file
# See https://github.com/HebiRobotics/robot-config/blob/main/README.adoc

# X-Series 4-DoF SCARA Arm with Gripper
version: 1.1
families: ["Arm"]
names: ["J1_base", "J2_shoulder", "J3_elbow", "J4_wrist"]
hrdf: "hrdf/A-2084-01G.hrdf"

gains:
  default: "gains/A-2084-01.xml"
  gripper: "gains/A-2080-01.xml"

feedback_frequency: 100 # [Hz]
command_lifetime: 0.25 # [s]

user_data:
  # IK Seed positions for inverse kinematics
  ik_seed_pos: [0.01, 1.0, 2.5, 1.5]

  # Home Position
  home_position: [0.0, 0.0, 0.0, 0.0]

  # Gripper specific settings
  has_gripper: true
  gripper_open_effort: 1
  gripper_close_effort: -5

plugins:
  - type: GravityCompensationEffort
    name: gravComp
    enabled: true
    ramp_time: 5

  - type: DynamicsCompensationEffort
    name: dynamicsComp
    enabled: true
    ramp_time: 5

  # Kits with a gas spring need to add a shoulder compensation torque.
  # It should be around -7 Nm for most kits, but it may need to be tuned
  # for your specific setup.
  - name: 'gasSpringCompensation'
    type: EffortOffset
    enabled: false
    ramp_time: 5
    offset: [0, -7, 0, 0]
