# T-Series 6-DoF Arm with Gripper
version: 1.0
families: ["Arm"]
names: ["J1_base", "J2_shoulder1A", "J3_shoulder2", "J4_elbow1", "J5_elbow2", "J6_wrist1", "J7_wrist2"]
hrdf: "hrdf/A-2582-01G.hrdf"

gains:
  default: "gains/A-2582-01.xml"
  gripper: "gains/A-2080-01.xml"

user_data:
  # Default seed positions for doing inverse kinematics
  ik_seed_pos: [0.01, -1, 0.01, 0.01, -1.5, 0.01, 0.01]

  # Gripper specific settings
  has_gripper: true
  gripper_open_effort: 1
  gripper_close_effort: -5

plugins:
  - type: GravityCompensationEffort
    name: gravComp
    enabled: true
    ramp_time: 5

  - type: DynamicsCompensationEffort
    name: dynamicsComp
    enabled: true
    ramp_time: 5

  - name: 'DoubleShoulder'
    type: DoubledJointMirror
    enabled: true
    group_Family: ["Arm"]
    group_name: ["J2_shoulder1B"]
    index: 2
