# HEBI Robot Config file
# See https://github.com/HebiRobotics/robot-config/blob/main/README.adoc

# T-Series 7-DoF Double Shoulder Arm
version: 1.1
families: ["Arm"]
names: ["J1_base", "J2A_shoulder1", "J3_shoulder2", "J4_elbow1", "J5_elbow2", "J6_wrist1", "J7_wrist2"]
hrdf: "hrdf/A-2582-07.hrdf"

gains:
  default: "gains/A-2582-07.xml"

feedback_frequency: 100 # [Hz]
command_lifetime: 0.25 # [s]

user_data:
  # IK Seed positions for inverse kinematics
  ik_seed_pos: [0.01, -1.0, 0.01, 2.0, 1.0, 1.57, 0.01]

  # Home Position
  home_position: [0.0, -1.2, 0.0, 2.3, 1.1, 1.57, 0.0]

plugins:
  - type: GravityCompensationEffort
    name: gravComp
    enabled: true
    ramp_time: 5

  - type: DynamicsCompensationEffort
    name: dynamicsComp
    enabled: true
    ramp_time: 5

  - name: 'DoubleShoulder'
    type: DoubledJointMirror
    enabled: true
    group_family: ["Arm"]
    group_name: [J2B_shoulder1"]
    index: 1
