# HEBI Robot Config file
# See https://github.com/HebiRobotics/robot-config/blob/main/README.adoc

# 6-DoF Arm
version: 1.1
families: ["Arm"]
names: ["J1_base", "J2_shoulder", "J3_elbow", "J4_wrist1", "J5_wrist2", "J6_wrist3"]
hrdf: "hrdf/A-2085-06.hrdf"

gains:
  default: "gains/A-2085-06.xml"

feedback_frequency: 100 # [Hz]
command_lifetime: 0.25 # [s]

plugins:
  - type: GravityCompensationEffort
    name: gravComp
    enabled: true
    ramp_time: 5

  - type: DynamicsCompensationEffort
    name: dynamicsComp
    enabled: true
    ramp_time: 5

user_data:
  # Three waypoints for Buttons - B1, B2, B3
  waypoint_1: [0, 0, 0, 0, 0, 0]
  waypoint_2: [0.7854, 1.0472, 2.0944, 1.0472, 0.7854, 0] # [pi/4, pi/3, 2*pi/3, pi/3, pi/4, 0]
  waypoint_3: [-0.7854, 1.0472, 2.0944, 1.0472, 2.356194490192345, 0] # [-pi/4, pi/3, 2*pi/3, pi/3, 3*pi/4, 0]

  # Time taken to travel to a waypoint
  travel_time: 3 # seconds

  mobile_io_family: "Arm"
  mobile_io_name: "mobileIO"
  mobile_io_layout: "layouts/ex_mobile_io_control.json"
